version: "2"

services:
  backend:
    container_name: horoscope
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run start"